name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'Dry run'
        required: true
        default: true
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-maven
        name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: install-gpg-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
#          gpg --list-secret-keys --keyid-format LONG
      - id: build
        name: Build
        run: ./mvnw --no-transfer-progress --batch-mode clean install
      - id: build-and-publish-to-central
        name: Build, sign and publish artifact to OSSRH
        if: ${{ ( github.event_name == 'release' && github.event.action == 'created' ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.dryrun != 'true' ) }}
        run: ./mvnw --no-transfer-progress --batch-mode -Prelease -Dmaven.test.skip=true clean install deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
